### ISSUE TITLE
Capitalization of mathjax-node has changed

### ISSUE THREAD

**Issue by Martin-Fuchs** [lierdakil/mathjax-pandoc-filter#1]
I've tried installing mathjax-pandoc-filter today with

```
npm i mathjax-pandoc-filter
```

however, I got the following error:

```
npm ERR! Invalid Package: expected MathJax-node but found mathjax-node
```

digging deeper into the MathJax-node changelog found this [commit](https://github.com/mathjax/MathJax-node/commit/26af9aecec4da006bcce0dc746e057fb42cae076) which changed the capitalization from "MathJax-node" to mathjax-node. 

Could you please fix the dependency in `package.json`? Thanks (and also: thanks for a very useful tool :-) )

**Comment by pkra** [comment]
Sorry for the inconvenience from the MathJax's team end.

**Comment by lierdakil** [comment]
v0.2.2 should do.
