### ISSUE TITLE
Embedded SVGs are not supported by WeasyPrint

### ISSUE THREAD

**Issue by pothos** [lierdakil/mathjax-pandoc-filter#3]
This here helps to render in WeasyPrint:

```
     svg = wait["for"](tex2svg, tex, inline);
+    svg = '<img src="data:image/svg+xml;charset=utf-8;base64,' + Buffer.from(svg).toString('base64') + '"/>';
     return pandoc.RawInline("html", inline ? svg : wrap(svg));
```

Maybe it could be configured by exposing a second filter executable (or passing an argument but I don't know if that works with pandoc's filter command line invokation)?

**Comment by lierdakil** [comment]
It's not the hardest thing to do, but `img` tags tend to be misaligned. Compare:
`img` tags:
![image](https://user-images.githubusercontent.com/7275622/41474459-b84c764c-70c4-11e8-9d7f-ecf0cef02298.png)
inline SVG:
![image](https://user-images.githubusercontent.com/7275622/41474495-cfc3f462-70c4-11e8-8aff-65a1b6b2a316.png)

**Comment by pothos** [comment]
Ah, which browser? Would `style="display: inline; vertical-align: middle;"` help?
Edit: Maybe fixing this depends on the browser, I don't need anything for it to work and adding something like my suggestion makes it worse in certain cases.

**Comment by pothos** [comment]
The solution is to copy the `width`, `height` and `style` attributes of the `svg` tag to the `img` tag…

**Comment by pothos** [comment]
```
    svg = wait["for"](tex2svg, tex, inline);
+   w = svg.match(/width="(.*?)"/)[0];
+   h = svg.match(/height="(.*?)"/)[0];
+   c = svg.match(/style="(.*?)"/)[0];
+   svg = '<img ' + w + ' ' + h + ' ' + c + ' src="data:image/svg+xml;charset=utf-8;base64,' + Buffer.from(svg).toString('base64') + '"/>';
    return pandoc.RawInline("html", inline ? svg : wrap(svg));
```

**Comment by pothos** [comment]
Webkit seems to have troubles with `<img width="3ex">` but this can be fixed with moving it to `<img style="width: 3ex;">` but I don't need this for WeasyPrint.

**Comment by lierdakil** [comment]
Huh. Cool, thanks for investigating. I've published v0.3.1. If you could test it and let me know if it works for you that would be great.

**Comment by lierdakil** [comment]
Note: please review https://github.com/lierdakil/mathjax-pandoc-filter#configuration

**Comment by pothos** [comment]
Thanks, perfect, it works same as my patch, both in WebKit and WeasyPrint :+1:
